services:
  web-starlink:
    container_name: web-starlink
    build: .
    restart: unless-stopped
    networks:
      - apps
    expose:
      - 80
    volumes:
      - ./:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.starlink-track.rule=Host(`starlinktrack.com`)
      - traefik.http.services.starlink-track.loadbalancer.server.port=80
      - traefik.http.routers.starlink-track.entrypoints=websecure
      - traefik.http.routers.starlink-track.tls.certresolver=myresolver

networks:
  apps:
    external: true