name: Auto city-mappings.json contribution merger

on:
  pull_request_target:
    types:
      - opened
      - synchronize
    paths:
      - 'app/static/other/city-mapping.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  validate:
    name: Validate Contribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Generate base file
        run: git show "${{ github.event.pull_request.base.sha }}:${{ 'app/static/other/city-mapping.json' }}" > "base_mapping.json"
      
      - name: Validation script
        run: python .github/workflows/city-mapping-json-merger.py

      - name: Merge
        if: success()
        run: gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
