name: Auto city-mappings.json contribution merger

on:
  pull_request_target:
    types:
      - opened
      - synchronize
    paths:
      - 'app/static/other/city-mapping.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  validate_and_merge:
    name: Validate and Merge Contribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Head with Full History
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Run Validation Script
        run: |
          git show "${{ github.event.pull_request.base.sha }}:${{ 'app/static/other/city-mapping.json' }}" > "base_mapping.json"

          python .github/workflows/city-mapping-json-merger.py

      - name: Enable Auto-Merge
        if: success()
        run: gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
