name: Auto city-mappings.json contribution merger

on:
  pull_request_target:
    types:
      - opened
      - synchronize
    paths:
      - 'app/static/other/city-mapping.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Security Check Validate File Size
        run: |
          FILE_PATH="app/static/other/city-mapping.json"
          MAX_SIZE=50000
          ACTUAL_SIZE=$(stat -c%s "$FILE_PATH")
          if [ "$ACTUAL_SIZE" -gt "$MAX_SIZE" ]; then
            echo "Security Risk: File size ($ACTUAL_SIZE bytes) exceeds the limit of $MAX_SIZE bytes."
            exit 1
          fi
          echo "File size is within limits."

      - name: Validate Contribution
        run: |
          FILE_PATH="app/static/other/city-mapping.json"
          if ! python -m json.tool "$FILE_PATH" > /dev/null; then
            echo "Validation failed: Invalid JSON format."
            exit 1
          fi

          BASE_COMMIT_SHA="${{ github.event.pull_request.base.sha }}"
          BASE_CONTENT=$(git show "${BASE_COMMIT_SHA}:${FILE_PATH}" || true)
          
          OLD_COUNT=$( [ -z "$BASE_CONTENT" ] && echo 0 || echo "$BASE_CONTENT" | jq 'length' )
          NEW_COUNT=$(jq 'length' "$FILE_PATH")
          ENTRIES_ADDED=$((NEW_COUNT - OLD_COUNT))

          echo "Net change: $ENTRIES_ADDED entries"
          if [ "$NEW_COUNT" -gt "$OLD_COUNT" ] && [ "$ENTRIES_ADDED" -le 2 ]; then
            echo "Validation passed: A valid number of entries were added."
            exit 0
          else
            echo "Validation failed: Change does not meet the criteria for auto-merging."
            exit 1
          fi

      - name: Enable Auto-Merge
        if: success()
        run: gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
